# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_error.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_userError(object):
    def setupUi(self, userError):
        userError.setObjectName("userError")
        userError.resize(414, 227)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Bao/Downloads/error_theapplication_2964.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        userError.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(userError)
        self.buttonBox.setGeometry(QtCore.QRect(50, 180, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label_2 = QtWidgets.QLabel(userError)
        self.label_2.setGeometry(QtCore.QRect(160, 110, 131, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(userError)
        self.label.setGeometry(QtCore.QRect(160, 70, 181, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(userError)
        self.label_3.setGeometry(QtCore.QRect(100, 70, 51, 61))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/Bao/Downloads/icons8-bell-curve-50.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(userError)
        self.label_4.setGeometry(QtCore.QRect(0, -10, 421, 291))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:/Users/Bao/Downloads/Untitled design.png"))
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.buttonBox.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()

        self.retranslateUi(userError)
        QtCore.QMetaObject.connectSlotsByName(userError)

    def retranslateUi(self, userError):
        _translate = QtCore.QCoreApplication.translate
        userError.setWindowTitle(_translate("userError", "Error"))
        self.label_2.setText(_translate("userError", "does not exist"))
        self.label.setText(_translate("userError", "Account information"))

